/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 28-Oct-2024 21:26:16
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB_Programa\extern\include\tmwtypes.h 
 */
const int N_L = 11;
const real64_T N[11] = {
    0.03495112791191,  0.05502909524806,  0.08551153938985,   0.1154009882297,
     0.1367983942365,   0.1446177099681,   0.1367983942365,   0.1154009882297,
    0.08551153938985,  0.05502909524806,  0.03495112791191
};
